services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - ${DOCKER_APP_PORT:-80}:8000
  db:
    image: mariadb:11.8-rc
    ports:
      -   ${DOCKER_DB_PORT:-3306}:3306
    volumes:
      -   db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}

volumes:
  db_data: